ALTER TABLE `{TABLEPREFIX}record` CHANGE `flag_1` `flag_1` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `{TABLEPREFIX}record` CHANGE `flag_2` `flag_2` TINYINT(4) NOT NULL DEFAULT '0';
ALTER TABLE `{TABLEPREFIX}record` CHANGE `flag_3` `flag_2` TINYINT(4) NOT NULL DEFAULT '0';

